name: zip-content-packs
on: [push]
jobs:
  zip-Renton_Municipal_Airport_Pack_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: ls -lR
      - run: pushd 'Renton Municipal Airport Pack 1' && zip -r '../Renton Municipal Airport Pack 1.zip' . && popd
      - run: ls -lR
      - uses: actions/upload-artifact@v3
        with:
          name: content-pack-artifacts
          path: 'Renton Municipal Airport Pack 1.zip'
          retention-days: 5
