name: zip-content-packs
on: [push]
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r 'Renton Municipal Airport Pack 1.zip' 'Renton Municipal Airport Pack 1'
