name: zip-content-packs
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Make release directory
        run: mkdir release
      - name: Checkout main
        uses: actions/checkout@master
      - name: Zip content packs
        run: ls -d *Pack* | while read directory; do pushd "${directory}" && zip -r ../"${directory}.zip" . && popd; done
      - name: List release directory
        run: ls -lR release
      - uses: actions/upload-artifact@v3
        with:
          name: content-pack-artifacts
          path: 'release'
          retention-days: 5
  