name: zip-content-packs
on: [push]
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -lR
      - uses: papeloto/action-zip@v1
        with:
          files: '*/'