name: zip-content-packs
on: [push]
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: '"Renton Municipal Airport Pack 1.zip"'
          directory: '"Renton Municipal Airport Pack 1"'
          exclusions: '*.git*'
