name: zip-content-packs
on: [push]
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: 'Renton\ Municipal\ Airport\ Pack\ 1/'
          dest: 'Renton\ Municipal\ Airport\ Pack\ 1.zip'
